### PR TITLE
bugfix-smb-dirs: /var/lib/samba/private, /var/log/samba/cores

### PR DESCRIPTION
**Pull request by grizmin**

### CODE REVIEW

**Comment by mbentley** [comment]
I’ll have to take a look; I hadn’t paid much attention to any errors as everything seemed to be working fine. Also, I don’t see anything you’re doing besides using arrays that actually requires bash right off the bat.  Unless there is a reason to add bash, I would prefer to keep it using sh. While it only saves a few MB in size, it’s a few MB.

**Comment by grizmin** [comment]
That's correct. Bash is there only because of the arrays. I don't like redundant code :)

That was the error:
`
timemachine    | Copyright Andrew Tridgell and the Samba Team 1992-2019
timemachine    | directory_create_or_exist: mkdir failed on directory /var/lib/samba/private/msg.sock: No such file or directory
timemachine    | directory_create_or_exist: mkdir failed on directory /var/log/samba/cores: No such file or directory
timemachine    | Failed to create /var/log/samba/cores for user 0 with mode 0700
timemachine    | Unable to setup corepath for nmbd: No such file or directory
timemachine    | nmbd version 4.11.5 started.
timemachine    | Copyright Andrew Tridgell and the Samba Team 1992-2019
timemachine    | directory_create_or_exist: mkdir failed on directory /var/lib/samba/private/msg.sock: No such file or directory
timemachine    | directory_create_or_exist: mkdir failed on directory /var/log/samba/cores: No such file or directory
timemachine    | Failed to create /var/log/samba/cores for user 0 with mode 0700
timemachine    | Unable to setup corepath for smbd: No such file or directory
timemachine    | smbd version 4.11.5 started.
timemachine    | Copyright Andrew Tridgell and the Samba Team 1992-2019
timemachine    | directory_create_or_exist: mkdir failed on directory /var/lib/samba/private/msg.sock: No such file or directory
timemachine    | directory_create_or_exist: mkdir failed on directory /var/log/samba/cores: No such file or directory
timemachine    | Failed to create /var/log/samba/cores for user 0 with mode 0700
timemachine    | Unable to setup corepath for nmbd: No such file or directory
timemachine    | nmbd version 4.11.5 started.
`

**Comment by grizmin** [comment]
But yeah, it's 4.1MB uncompressed/1.15MB compressed. Well, you use the pull request as a issue record.

**Comment by grizmin** [comment]
bash dependency removed.

**Comment by mbentley** [comment]
Awesome, like the function mkdir and chown cleanup.  I haven’t had a chance to test but just adding a directory certainly won’t impact anything in a negative way.  Thanks for the PR!  LTGM

**Comment by mbentley** [comment]
Upon further inspection, this is likely to only occur if you're utilizing a bind mounted volume as the directories, while they do not exist, can be created just fine as we have the correct permissions with using docker managed volumes.  That's why I hadn't seen that in my logs previously.  Either way, it's not terrible to have a sanity check so thank you.

**Pull request merged**
